### ISSUE TITLE
Correct S3 bucket issue caused by Python 2.7.9 update 

### ISSUE THREAD

**Issue by jbmartin** [stitchfix/splits#9]
Python introduced strict certificate checking in version 2.7.9 (see [PEP 476](https://www.python.org/dev/peps/pep-0476/)) that causes buckets with dots in their names to fail on load e.g.,

```
> boto.s3.get_bucket('my.bucket')
ssl.CertificateError: hostname 'my.bucket.s3.amazonaws.com' doesn't match either of'*.s3.amazonaws.com', 's3.amazonaws.com'
```

More at boto/boto/issues/2836.

**Comment by ilanbm** [comment]
Any solution?

**Comment by jbmartin** [comment]
@ilanbm PR #10 that fixed it on my end.

**Comment by ironmanMA** [comment]
issue fixed with setting the calling-format

something like 
s3_conn = boto.connect_s3(AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, calling_format=OrdinaryCallingFormat())

https://github.com/boto/boto/issues/2836
